/**
 * Authoritative ISO-2 → VeSIM regional destination code.
 * Used when destination.regions metadata is empty (common on LIVE).
 * Only maps onto regional catalogs that exist in the VeSIM destinations list.
 * No entry ⇒ no recommendation (never invent a region).
 */

export const VESIM_REGIONAL_CODES = [
  "region-africa",
  "region-asia",
  "region-caribbean",
  "region-central-america",
  "region-eastern-europe",
  "region-middle-east-and-north-africa",
  "region-north-america",
  "region-oceania",
  "region-western-europe",
] as const;

export type VesimRegionalCode = (typeof VESIM_REGIONAL_CODES)[number];

/** Skip generic / non-geographic regional buckets. */
export function isRecommendableRegionalCode(code: string): boolean {
  const normalized = code.trim().toLowerCase();
  return (VESIM_REGIONAL_CODES as readonly string[]).includes(normalized);
}

/**
 * Primary regional catalog for a country ISO-2 code.
 * Aligned to VeSIM `region-*` destinations (not UN labels alone).
 */
const COUNTRY_TO_REGIONAL_CODE: Record<string, VesimRegionalCode> = {
  // Africa
  AO: "region-africa",
  BJ: "region-africa",
  BW: "region-africa",
  BF: "region-africa",
  BI: "region-africa",
  CV: "region-africa",
  CM: "region-africa",
  CF: "region-africa",
  TD: "region-africa",
  KM: "region-africa",
  CG: "region-africa",
  CD: "region-africa",
  CI: "region-africa",
  DJ: "region-africa",
  GQ: "region-africa",
  ER: "region-africa",
  SZ: "region-africa",
  ET: "region-africa",
  GA: "region-africa",
  GM: "region-africa",
  GH: "region-africa",
  GN: "region-africa",
  GW: "region-africa",
  KE: "region-africa",
  LS: "region-africa",
  LR: "region-africa",
  MG: "region-africa",
  MW: "region-africa",
  ML: "region-africa",
  MR: "region-africa",
  MU: "region-africa",
  YT: "region-africa",
  MZ: "region-africa",
  NA: "region-africa",
  NE: "region-africa",
  NG: "region-africa",
  RW: "region-africa",
  ST: "region-africa",
  SN: "region-africa",
  SC: "region-africa",
  SL: "region-africa",
  SO: "region-africa",
  ZA: "region-africa",
  SS: "region-africa",
  SH: "region-africa",
  SD: "region-africa",
  TZ: "region-africa",
  TG: "region-africa",
  UG: "region-africa",
  ZM: "region-africa",
  ZW: "region-africa",
  IC: "region-africa",

  // Asia
  AF: "region-asia",
  AM: "region-asia",
  AZ: "region-asia",
  BD: "region-asia",
  BT: "region-asia",
  BN: "region-asia",
  KH: "region-asia",
  CN: "region-asia",
  GE: "region-asia",
  HK: "region-asia",
  IN: "region-asia",
  ID: "region-asia",
  JP: "region-asia",
  KZ: "region-asia",
  KG: "region-asia",
  LA: "region-asia",
  MO: "region-asia",
  MY: "region-asia",
  MV: "region-asia",
  MN: "region-asia",
  MM: "region-asia",
  NP: "region-asia",
  KP: "region-asia",
  KR: "region-asia",
  PK: "region-asia",
  PH: "region-asia",
  SG: "region-asia",
  LK: "region-asia",
  TW: "region-asia",
  TJ: "region-asia",
  TH: "region-asia",
  TL: "region-asia",
  TM: "region-asia",
  UZ: "region-asia",
  VN: "region-asia",

  // Caribbean
  AI: "region-caribbean",
  AG: "region-caribbean",
  AW: "region-caribbean",
  BS: "region-caribbean",
  BB: "region-caribbean",
  BQ: "region-caribbean",
  VG: "region-caribbean",
  KY: "region-caribbean",
  CU: "region-caribbean",
  CW: "region-caribbean",
  DM: "region-caribbean",
  DO: "region-caribbean",
  GD: "region-caribbean",
  GP: "region-caribbean",
  HT: "region-caribbean",
  JM: "region-caribbean",
  MQ: "region-caribbean",
  MS: "region-caribbean",
  PR: "region-caribbean",
  BL: "region-caribbean",
  KN: "region-caribbean",
  LC: "region-caribbean",
  MF: "region-caribbean",
  VC: "region-caribbean",
  SX: "region-caribbean",
  TT: "region-caribbean",
  TC: "region-caribbean",
  VI: "region-caribbean",

  // Central America
  BZ: "region-central-america",
  CR: "region-central-america",
  SV: "region-central-america",
  GT: "region-central-america",
  HN: "region-central-america",
  NI: "region-central-america",
  PA: "region-central-america",

  // Eastern Europe
  BY: "region-eastern-europe",
  BA: "region-eastern-europe",
  BG: "region-eastern-europe",
  CZ: "region-eastern-europe",
  EE: "region-eastern-europe",
  HU: "region-eastern-europe",
  LV: "region-eastern-europe",
  LT: "region-eastern-europe",
  MD: "region-eastern-europe",
  ME: "region-eastern-europe",
  MK: "region-eastern-europe",
  PL: "region-eastern-europe",
  RO: "region-eastern-europe",
  RU: "region-eastern-europe",
  RS: "region-eastern-europe",
  SK: "region-eastern-europe",
  SI: "region-eastern-europe",
  UA: "region-eastern-europe",
  XK: "region-eastern-europe",
  AL: "region-eastern-europe",

  // Middle East and North Africa
  DZ: "region-middle-east-and-north-africa",
  BH: "region-middle-east-and-north-africa",
  EG: "region-middle-east-and-north-africa",
  IR: "region-middle-east-and-north-africa",
  IQ: "region-middle-east-and-north-africa",
  IL: "region-middle-east-and-north-africa",
  JO: "region-middle-east-and-north-africa",
  KW: "region-middle-east-and-north-africa",
  LB: "region-middle-east-and-north-africa",
  LY: "region-middle-east-and-north-africa",
  MA: "region-middle-east-and-north-africa",
  OM: "region-middle-east-and-north-africa",
  PS: "region-middle-east-and-north-africa",
  QA: "region-middle-east-and-north-africa",
  SA: "region-middle-east-and-north-africa",
  SY: "region-middle-east-and-north-africa",
  TN: "region-middle-east-and-north-africa",
  AE: "region-middle-east-and-north-africa",
  YE: "region-middle-east-and-north-africa",
  TR: "region-middle-east-and-north-africa",

  // North America
  CA: "region-north-america",
  MX: "region-north-america",
  US: "region-north-america",

  // Oceania
  AS: "region-oceania",
  AU: "region-oceania",
  CK: "region-oceania",
  FJ: "region-oceania",
  PF: "region-oceania",
  GU: "region-oceania",
  KI: "region-oceania",
  MH: "region-oceania",
  FM: "region-oceania",
  NR: "region-oceania",
  NC: "region-oceania",
  NZ: "region-oceania",
  NU: "region-oceania",
  MP: "region-oceania",
  PW: "region-oceania",
  PG: "region-oceania",
  PN: "region-oceania",
  WS: "region-oceania",
  SB: "region-oceania",
  TK: "region-oceania",
  TO: "region-oceania",
  TV: "region-oceania",
  VU: "region-oceania",
  WF: "region-oceania",

  // Western Europe
  AD: "region-western-europe",
  AT: "region-western-europe",
  BE: "region-western-europe",
  HR: "region-western-europe",
  CY: "region-western-europe",
  DK: "region-western-europe",
  FI: "region-western-europe",
  FR: "region-western-europe",
  DE: "region-western-europe",
  GI: "region-western-europe",
  GR: "region-western-europe",
  GG: "region-western-europe",
  IS: "region-western-europe",
  IE: "region-western-europe",
  IM: "region-western-europe",
  IT: "region-western-europe",
  JE: "region-western-europe",
  LI: "region-western-europe",
  LU: "region-western-europe",
  MT: "region-western-europe",
  MC: "region-western-europe",
  NL: "region-western-europe",
  NO: "region-western-europe",
  PT: "region-western-europe",
  SM: "region-western-europe",
  ES: "region-western-europe",
  SE: "region-western-europe",
  CH: "region-western-europe",
  GB: "region-western-europe",
  VA: "region-western-europe",
  FO: "region-western-europe",
  AX: "region-western-europe",
};

export function regionalCodeForCountryIso(
  countryCode: string | null | undefined
): VesimRegionalCode | undefined {
  const iso = (countryCode || "").trim().toUpperCase();
  if (!iso || iso.length !== 2) return undefined;
  return COUNTRY_TO_REGIONAL_CODE[iso];
}
